version: "3.8"

services:
  frontend:
    container_name: kitt4sme-digital-datasheets-frontend
    image: ryankford/digital-datasheets:1.0.3-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000