version: "3.8"

services:

  backend:
    container_name: kitt4sme-digital-datasheets-backend
    image: ryankford/digital-datasheets:1.0-backend
    build: .
    ports:
      - '5000:5000'
    environment:
      - POSTGRES_DB_USER=$POSTGRES_DB_USER
      - POSTGRES_DB_PASS=$POSTGRES_DB_PASS
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB_NAME=$POSTGRES_DB_NAME
      - POSTGRES_USE_SSL=$POSTGRES_USE_SSL
      - VALIDATION_URL=https://ramp.eu/ms/component/api/v1/component/